### ISSUE TITLE
Schedule and Intro Meeting & Create Agenda

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/university#6]
We'd like to schedule an introductory meeting with the folks from BUGS and some of the folks from RPI.

Here is a poll for the meeting time, please fill it out ASAP if you'd like to attend! https://doodle.com/poll/ivt5rp5dnxvsic8v#calendar

We should have an agenda prepared for the meeting. If you'd like to suggest agenda items, please comment here :)

**Comment by kburk1997** [comment]
My comment in issue #5 addressed the fact that we do not have a consistent YACS Code of Conduct. A potential agenda item is to review the modified versions of Contributor Covenant and RCOS Community Codes of Conduct and create a Code of Conduct that is compatible with RPI and NYU (having policies of enforcement defined for each university), and in the future allow space for more universities to add their own amendments to the Code of Conduct.

**Comment by Bad-Science** [comment]
For the record, the meeting has been scheduled for (today) Wednesday, March 7 @ 12PM EST.

The agenda is as follows:
- Introductions
- Review proposal from #2 and suggest changes as needed
- Overview of application / code structure
- Overview of important repos and development practices (yacs-web, yacs-orchestra)
- Answer questions
- Overview of Code of Conduct

Meeting minutes will be posted here, and then this issue can be closed.

**Comment by Bad-Science** [comment]
Added meeting minutes as of b95f092. Thanks for coming everyone!
