### ISSUE TITLE
Create project-wide Code of Conduct

### ISSUE THREAD

**Issue by kburk1997** [YACS-RCOS/university#7]
As mentioned previously, the Code of Conduct across repositories (and universities!) is inconsistent. 

During today's meeting, the [Project Template](https://github.com/rcos/intro/blob/master/docs/project_coc_template.md) for the RCOS Community Code of Conduct was introduced and once any NYU-specific policies are added to "project-specific guidelines", we should be set to use this template as a starting point for a universal Code of Conduct for YACS unless there is a strong case for using the [Contributor Covenant](https://github.com/YACS-RCOS/yacs-web/blob/master/CODE_OF_CONDUCT.md) instead (used in yacs and yacs-web).

Note that if we use the Contributor Covenant, all incident handling responsibilities will be delegated to YACS team leads, which may conflict with university-specific policies on handling misconduct within clubs. However, the RCOS Community Code of Conduct keeps university-specific policies and university-agnostic policies in mind.

**Comment by Bad-Science** [comment]
Closing this since we are deprecating this repo and moving to a mono-repo.
